### ISSUE TITLE
Quelle technologie de BD utiliser ?

### ISSUE THREAD

**Issue by kilian-goetz** [Neighbook/Backend#1]
Bonjour @UTBM-FISA-TutoredProject/backend-engineers,

J'ouvre l'issue ici car c'est plus du domaine du backend. Il faut que l'on se décide sur quelle technologie de base de données utiliser ? Il faut que l'on sache assez tôt pour que l'équipe infrastructure puisse savoir quel service azure utiliser.

**Comment by Beladric** [comment]
Bonjour @UTBM-FISA-TutoredProject/backend-engineers,

J'ouvre l'issue ici car c'est plus du domaine du backend. Il faut que l'on se décide sur quelle technologie de base de données utiliser ? Il faut que l'on sache assez tôt pour que l'équipe infrastructure puisse savoir quel service azure utiliser.

**Comment by Valentin271** [comment]
Je pense qu'on peut utiliser MySQL pour la prod, c'est un peu un standard et tous le monde l'a vu à l'UTBM (bien que ça ne soit pas vraiment utile).

En dev je propose aussi MySQL, histoire de pas avoir de problème de déploiement. En plus c'est facile à mettre en place avec un docker-compose.

**Comment by follyjohn** [comment]
@Valentin271 le MySql étais très utilisé mais moi je suggère d'utilisé **PostgreSql**, c'est un MySql++, avec :
- de meilleures performances en requettage complexe, en écriture...
- possibilité d'utiliser des objet en base de donnée (ORDBMS)
- plus de functions
- des fonctionnalités de sécurité en plus 
- le fait que PostgreSql soit sous une licence plus proche de MIT

**Comment by kilian-goetz** [comment]
Bonjour @UTBM-FISA-TutoredProject/backend-engineers,

**❗ Je clôt cette issue ❗** la technologie utilisé a été décidé dans le [sondage](https://github.com/UTBM-FISA-TutoredProject/.github/discussions/7).

Merci à tout ceux ayant participé à cette issue 😄.
