### ISSUE TITLE
Problèmes de rôle dans l'AAD

### ISSUE THREAD

**Issue by follyjohn** [Neighbook/Backend#24]
# Comportement souhaité

L'ensemble de l'équipe infrastructure doit pouvoir déployer sur la souscription Azure.

# Comportement actuel

Des droits sont manquants pour la plupart des membres de l'équipe infrastructure, ce qui les empêches de déployer les ressources.

## Étapes à suivre

Donner les droits nécessaires dans l'Azure Active Directory.

# Liste de vérification

- [x] Je suis bien sur la dernière version du projet.
- [x] J'ai bien vérifié la documentation et je n'y ai pas trouvé de réponse.
- [x] Je me suis assuré qu'il n'y a pas d'autre rapport concernant la même erreur.
- [x] J'ai vérifié que je suis dans le bon ***repositories*** avant de créer le rapport d'erreur.

**Comment by kilian-goetz** [comment]
Salut @follyjohn,

Cette issue à plus de deux mois. Où en sont les travaux concernant ces problèmes ? Quels sont exactement les problèmes rencontrés ? Car il n'y a pas de description fournie. De surcroît, on va héberger sur les serveurs de l'UTBM ce semestre, donc l'AAD n'est plus un souci ^^.
