### ISSUE TITLE
Création d'un docker compose

### ISSUE THREAD

**Issue by PerdrieauC** [Neighbook/Backend#42]
### Résumé

Création d'un docker compose.

### Motivation

Les environnements de travail étant très hétérogène dans notre promotion, il est compliqué pour chacun de lancer le projet correctement sans erreurs.

### Implémentation

L'implémentation d'un docker compose permettrait de pallier ce problème.

**Comment by kilian-goetz** [comment]
Salut @PerdrieauC,

Encore merci pour ton investissement. On va travailler davantage avec docker ce semestre, @Valentin271et @yaminabes travail sur le docker compose afin qu'on puisse avoir tous une seule et même manière de travailler en dev. Peux-tu utiliser les templates des issues s'il te plaît, pour le formalisme. Je vais changer l'assigné et te mettre en relation avec @Valentin271 et @yaminabes.

**Comment by Valentin271** [comment]
@Beladric close pls
