### ISSUE TITLE
Info de clé dupliquée sur la route /auth/register 

### ISSUE THREAD

**Issue by Nathan-Kr** [Neighbook/Backend#46]
Lorsque l'on veut s'inscrire avec un email ou un nom d'utilisateur déjà utilisé, la requete renvoie une erreur 500 sans plus de précision. 
Pour le formulaire d'inscription il faudrait pouvoir dire à l'utilisateur quel champ doit être changé
![image](https://user-images.githubusercontent.com/66138267/216821426-57a76159-7380-43aa-898a-11f6005b06f5.png)

**Comment by follyjohn** [comment]
Je crois qu'on a resolut ceci dans une #44
